LocalizationManager:add_localized_strings({
	["menu_tech_rework"] = "Unlocking the Technician",
	["menu_tech_rework_desc"] = "The Technician is an expert in the practical application of criminal science, enjoying anything that goes BOOM!\n\nSpending the first point in the Technician skill tree unlocks the ability to place the trip mine deployable. The trip mine can be used to blow things up, like people and safes.\n\n$multibasic; trip mines are added to your inventory.\nTrip mines can be turned on and off.",
	["menu_technician_left_1"] = "Unavailable",
	["menu_technician_left_1_desc"] = "This skill has not been completed and is not recommended to be specialized in",
	["menu_technician_mid_1"] = "Combat Engineer",
	["menu_technician_mid_1_desc"] = "BASIC: 1 point / $4,500\nUpgrades your trip mines with a sensor mode, highlighting enemies that walk past. During stealth, the trip mines will highlight guards and special enemies for your crew.\n\nIf stealth is not an option, the trip mines will highlight special enemies for you and your crew.\n\nACE: 3 points / $12,500\nSpecial enemies marked by your trip mines take 15% more damage",
	["menu_technician_right_1"] = "Nerves of Steel",
	["menu_technician_right_1_desc"] = "",
	["menu_technician_left_2"] = "Unavailable",
	["menu_technician_left_2_desc"] = "This skill has not been completed and is not recommended to be specialized in",
	["menu_technician_mid_2"] = "Blast Radius",
	["menu_technician_mid_2_desc"] = "BASIC: 1 point / $28,500\nThe radius of trip mine explosions are increased by 30%\n\nACE: 3 points / $84,500\nThe radius of trip mine explosions are increased by an additional 70%",
	["menu_technician_right_2"] = "Hardware Expert",
	["menu_technician_right_2_desc"] = "BASIC: 1 point / $28,500\nYou fix the drill 25% faster and you also deploy trip mines 40% faster.\n\nACE: 3 points / $84,500\nGives your drill a 30% chance to autorestart when it breaks down. You also deploy the sentry gun 50% faster.",
	["menu_technician_left_3"] = "Sentry Gun",
	["menu_technician_left_3_desc"] = "BASIC: 1 point / $56,500\nUnlocks the sentry gun for you to use.\n\nACE: 3 points / $168,500\nYour sentry gun accuracy is increased by 100% and it's rotational speed is increased by 150%",
	["menu_technician_mid_3"] = "Jack of All Trades",
	["menu_technician_mid_3_desc"] = "BASIC: 1 point / $56,500\nThis has not been implemented yet\n\nACE: 3 points / $168,500\nYou can carry sentry guns and trip mines at the same time. When you deplete your trip mines or sentry guns you will switch to the other one.\n\nNote: You need a sentry gun for this skill to work.",
	["menu_technician_right_3"] = "",
	["menu_technician_right_3_desc"] = "",
	["menu_technician_left_4"] = "Sentry Combat Upgrade",
	["menu_technician_left_4_desc"] = "BASIC: 4 points / $336,500\nYour sentry gun is loaded with 50% extra ammo.\n\nACE: 8 points / $672,500\nYou can now reload your sentry gun with your own ammo.",
	["menu_technician_mid_4"] = "Shaped Charge",
	["menu_technician_mid_4_desc"] = "BASIC: 4 points / $336,500\nTrip mines can now be converted to shaped charges, used to breach certain safes and doors.\n\nACE: 8 points / $672,500\nAdds 4 more trip mines to your inventory.",
	["menu_technician_right_4"] = "",
	["menu_technician_right_4_desc"] = "",
	["menu_technician_left_5"] = "Sentry Tower Defense",
	["menu_technician_left_5_desc"] = ""
	
})